# -*- coding: utf-8 -*-
from multiprocessing import cpu_count
from pathlib import Path
from shutil import which

BOT_NAME = 'leovendo'

SPIDER_MODULES = ['leovendo.spiders']
NEWSPIDER_MODULE = 'leovendo.spiders'


# Crawl responsibly by identifying yourself (and your website) on the user-agent
# USER_AGENT = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36'

# Obey robots.txt rules
ROBOTSTXT_OBEY = True

# Configure maximum concurrent requests performed by Scrapy (default: 16)
CONCURRENT_REQUESTS = cpu_count()

# Configure a delay for requests for the same website (default: 0)
# See https://docs.scrapy.org/en/latest/topics/settings.html#download-delay
# See also autothrottle settings and docs
#DOWNLOAD_DELAY = 3
# The download delay setting will honor only one of:
#CONCURRENT_REQUESTS_PER_DOMAIN = 16
#CONCURRENT_REQUESTS_PER_IP = 16

# Disable cookies (enabled by default)
#COOKIES_ENABLED = False

# Disable Telnet Console (enabled by default)
#TELNETCONSOLE_ENABLED = False

# Override the default request headers:
#DEFAULT_REQUEST_HEADERS = {
#   'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
#   'Accept-Language': 'en',
#}

# Enable or disable spider middlewares
# SPIDER_MIDDLEWARES = {
#    'leovendo.middlewares.SpiderExceptionHandler': 543,
# }

# Enable or disable downloader middlewares
DOWNLOADER_MIDDLEWARES = {
    'leovendo.middlewares.SeleniumMiddleware': 800,
    'scrapy.downloadermiddlewares.retry.RetryMiddleware': 500
}

# Enable or disable extensions
#EXTENSIONS = {
#    'scrapy.extensions.telnet.TelnetConsole': None,
#}

# Configure item pipelines
ITEM_PIPELINES = {
   'leovendo.pipelines.GoogleSheetExportPipeline': 300,
}

# Enable and configure the AutoThrottle extension (disabled by default)
AUTOTHROTTLE_ENABLED = True
# The initial download delay
AUTOTHROTTLE_START_DELAY = 5
# The maximum download delay to be set in case of high latencies
AUTOTHROTTLE_MAX_DELAY = 60
# The average number of requests Scrapy should be sending in parallel to
# each remote server
AUTOTHROTTLE_TARGET_CONCURRENCY = 2.0
# Enable showing throttling stats for every response received:
#AUTOTHROTTLE_DEBUG = False

# Enable and configure HTTP caching (disabled by default)
#HTTPCACHE_ENABLED = True
#HTTPCACHE_EXPIRATION_SECS = 0
#HTTPCACHE_DIR = 'httpcache'
#HTTPCACHE_IGNORE_HTTP_CODES = []
#HTTPCACHE_STORAGE = 'scrapy.extensions.httpcache.FilesystemCacheStorage'

# FEED_FORMAT = 'csv'
# FEED_URI = 'exports/yahoo_finance.csv'

# scrapy-selenium settings
SELENIUM_DRIVER_NAME = 'chrome'
PROJECT_DRIVER_PATH = str(Path('leovendo/drivers/windows/chromedriver.exe').resolve())
SELENIUM_DRIVER_EXECUTABLE_PATH = which('chromedriver') or PROJECT_DRIVER_PATH
SELENIUM_DRIVER_ARGUMENTS = ['--headless', '--disable-gpu', '--start-maximized', '--window-size=1366,768']

# Google Sheet settings
SPREADSHEET_NAME = 'Stocks Value'
WORKSHEET_NAME = 'test'

# tickers to scrape
TICKERS = [
    'AXP',
    'AAPL',
    'BA',
    'CAT',
    'CSCO',
    'CVX',
    'XOM',
    'GS',
    'HD',
    'IBM',
    'INTC',
    'JNJ',
    'KO',
    'JPM',
    'MCD',
    'MMM',
    'MRK',
    'MSFT',
    'NKE',
    'PFE',
    'PG',
    'TRV',
    'UNH',
    'UTX',
    'VZ',
    'V',
    'WBA',
    'WMT',
    'DIS',
    'ATVI',
    'ADBE',
    'AMD', 
    'ALGN', 
    'ALXN', 
    'AMZN', 
    'AMGN', 
    'AAL', 
    'ADI', 
    'AMAT', 
    'ASML', 
    'ADSK', 
    'ADP', 
    'AVGO', 
    'BIDU', 
    'BIIB', 
    'BMRN', 
    'CDNS', 
    'CERN', 
    'CHKP', 
    'CHTR', 
    'TCOM', 
    'CTAS', 
    'CTXS', 
    'CMCSA', 
    'COST', 
    'CSX', 
    'CTSH', 
    'DLTR', 
    'EA', 
    'EBAY', 
    'EXC', 
    'EXPE', 
    'FAST', 
    'FB', 
    'FISV', 
    'GILD', 
    'GOOG', 
    'GOOGL', 
    'HAS', 
    'HSIC', 
    'ILMN', 
    'INCY', 
    'INTU', 
    'ISRG', 
    'IDXX', 
    'JBHT', 
    'JD', 
    'KLAC', 
    'KHC', 
    'LRCX', 
    'LBTYA', 
    'LBTYK', 
    'LULU', 
    'MELI', 
    'MAR', 
    'MCHP', 
    'MDLZ', 
    'MNST', 
    'MU', 
    'MXIM', 
    'MYL', 
    'NTAP', 
    'NFLX', 
    'NTES', 
    'NVDA', 
    'NXPI', 
    'ORLY', 
    'PAYX', 
    'PCAR', 
    'BKNG', 
    'PYPL', 
    'PEP', 
    'QCOM', 
    'REGN', 
    'ROST', 
    'SIRI', 
    'SWKS', 
    'SBUX', 
    'NLOK', 
    'SNPS', 
    'TTWO', 
    'TSLA', 
    'TXN', 
    'TMUS', 
    'ULTA', 
    'UAL', 
    'VRSN', 
    'VRSK', 
    'VRTX', 
    'WDC', 
    'WDAY', 
    'WYNN', 
    'XEL', 
    'XLNX', 
    'BRK.B', 
    'MA', 
    'BAC', 
    'T', 
    'WFC', 
    'C', 
    'CRM', 
    'ABT', 
    'MDT', 
    'BMY', 
    'ABBV', 
    'PM', 
    'NEE', 
    'TMO', 
    'ACN', 
    'HON', 
    'UNP', 
    'ORCL', 
    'LIN', 
    'LLY', 
    'AMT', 
    'GE', 
    'LMT', 
    'DHR', 
    'FIS', 
    'LOW', 
    'CVS', 
    'MO', 
    'CI', 
    'USB', 
    'TJX', 
    'CME', 
    'ANTM', 
    'SPGI', 
    'CB', 
    'UPS', 
    'DUK', 
    'TFC', 
    'SO', 
    'PLD', 
    'D', 
    'SYK', 
    'BDX', 
    'MS', 
    'CCI', 
    'ZTS', 
    'PNC', 
    'NOW', 
    'BLK', 
    'CL', 
    'AGN', 
    'COP', 
    'RTN', 
    'GPN', 
    'MMC', 
    'TGT', 
    'BSX', 
    'NOC', 
    'APD', 
    'EQIX', 
    'AON', 
    'ITW', 
    'NSC', 
    'SCHW', 
    'ICE', 
    'DE', 
    'ECL', 
    'AEP', 
    'LHX', 
    'KMB', 
    'HUM', 
    'WM', 
    'PGR', 
    'SHW', 
    'EL', 
    'EW', 
    'COF', 
    'SLB', 
    'BAX', 
    'SRE', 
    'MCO', 
    'EMR', 
    'GD', 
    'GM', 
    'EOG', 
    'ETN', 
    'SPG', 
    'KMI', 
    'AIG', 
    'MET', 
    'ROP', 
    'ALL', 
    'DG', 
    'SYY', 
    'PSX', 
    'HCA', 
    'DD', 
    'AFL', 
    'BK', 
    'PRU', 
    'MPC', 
    'FDX', 
    'CNC', 
    'OXY', 
    'WELL', 
    'DOW', 
    'NEM', 
    'IR', 
    'PSA', 
    'DAL', 
    'STZ', 
    'VLO', 
    'SBAC', 
    'HPQ', 
    'ZBH', 
    'JCI', 
    'INFO', 
    'TROW', 
    'GIS', 
    'TDG', 
    'YUM', 
    'HLT', 
    'WEC', 
    'F', 
    'AVB', 
    'OKE', 
    'MSI', 
    'TEL', 
    'ED', 
    'APH', 
    'MCK', 
    'EQR', 
    'ES', 
    'IQV', 
    'PEG', 
    'TWTR', 
    'STT', 
    'PPG', 
    'FE', 
    'EIX', 
    'LUV', 
    'VFC', 
    'WLTW', 
    'FLT', 
    'DLR', 
    'PH', 
    'MSCI', 
    'ETR', 
    'A', 
    'O', 
    'WMB', 
    'DTE', 
    'CMI', 
    'PPL', 
    'BLL', 
    'SWK', 
    'RMD', 
    'AZO', 
    'AWK', 
    'ANSS', 
    'ADM', 
    'DFS', 
    'HSY', 
    'TSN', 
    'CMG', 
    'ROK', 
    'PXD', 
    'LVS', 
    'AME', 
    'CTVA', 
    'FTV', 
    'WY', 
    'AMP', 
    'APTV', 
    'KR', 
    'MTB', 
    'VTR', 
    'GLW', 
    'CBRE', 
    'NTRS', 
    'LYB', 
    'HIG', 
    'RSG', 
    'ESS', 
    'BXP', 
    'CPRT', 
    'AEE', 
    'FITB', 
    'DHI', 
    'CLX', 
    'BBY', 
    'MKC', 
    'ARE', 
    'AJG', 
    'SYF', 
    'CDW', 
    'FRC', 
    'LEN', 
    'EFX', 
    'KEY', 
    'HAL', 
    'CMS', 
    'VMC', 
    'RCL', 
    'LH', 
    'HPE', 
    'VIAC', 
    'MTD', 
    'CHD', 
    'KEYS', 
    'PEAK', 
    'TFX', 
    'FCX', 
    'CAH', 
    'CINF', 
    'KSU', 
    'DOV', 
    'COO', 
    'OMC', 
    'IP', 
    'CCL',
    'FTNT', 
    'K', 
    'CFG', 
    'AMCR', 
    'EVRG', 
    'MAA', 
    'MGM', 
    'MLM', 
    'KMX', 
    'AKAM', 
    'RF', 
    'CAG', 
    'XYL', 
    'HES', 
    'CXO', 
    'PAYC', 
    'LDOS', 
    'DGX', 
    'DRI', 
    'UDR', 
    'EXR', 
    'HBAN', 
    'PFG', 
    'IFF', 
    'ATO', 
    'TIF', 
    'NUE', 
    'ABC', 
    'STE', 
    'BKR', 
    'GRMN', 
    'HOLX', 
    'DRE', 
    'ODFL', 
    'L', 
    'LNT', 
    'WAB', 
    'GPC', 
    'CBOE', 
    'BR', 
    'WAT', 
    'LW', 
    'NVR', 
    'FMC', 
    'AES', 
    'SIVB', 
    'J', 
    'GWW', 
    'CNP', 
    'IT', 
    'NDAQ', 
    'VAR', 
    'CTL', 
    'CE', 
    'FOXA', 
    'HRL', 
    'MAS', 
    'JKHY', 
    'IEX', 
    'MKTX', 
    'BF.B', 
    'ALLE', 
    'XRAY', 
    'ARNC', 
    'ZBRA', 
    'EXPD', 
    'STX', 
    'SJM', 
    'QRVO', 
    'HST', 
    'LNC', 
    'RJF', 
    'FANG', 
    'ANET', 
    'PHM', 
    'URI', 
    'RE', 
    'TSCO', 
    'AVY', 
    'WRB', 
    'UHS', 
    'NCLH', 
    'PNW', 
    'NI', 
    'GL', 
    'WU', 
    'TXT', 
    'VNO', 
    'REG', 
    'PKI', 
    'LYV', 
    'WRK', 
    'TAP', 
    'APA', 
    'LKQ', 
    'EMN', 
    'DISH', 
    'HII', 
    'FBHS', 
    'NRG', 
    'ETFC', 
    'CHRW', 
    'DISCK', 
    'ALB', 
    'WHR', 
    'IRM', 
    'IPG', 
    'PKG', 
    'AAP',
    'NBL', 
    'CMA', 
    'FRT', 
    'DVN', 
    'AIZ', 
    'NOV', 
    'SNA', 
    'MRO', 
    'CF', 
    'JNPR', 
    'MHK', 
    'CPB', 
    'AIV', 
    'ALK', 
    'TPR', 
    'DXC', 
    'KIM', 
    'ZION', 
    'PRGO', 
    'SLG', 
    'DVA', 
    'NWL', 
    'FLIR', 
    'FFIV', 
    'ABMD', 
    'NLSN', 
    'PNR', 
    'FTI', 
    'PBCT', 
    'XRX', 
    'RHI', 
    'KSS', 
    'BWA', 
    'BEN', 
    'IVZ', 
    'PVH', 
    'HFC', 
    'MOS', 
    'UNM', 
    'COG', 
    'AOS', 
    'RL', 
    'FOX', 
    'FLS', 
    'LEG', 
    'PWR', 
    'ROL', 
    'NWSA', 
    'LB', 
    'HOG', 
    'SEE', 
    'HBI', 
    'M', 
    'HP', 
    'IPGP', 
    'DISCA', 
    'HRB', 
    'CPRI', 
    'JWN', 
    'ADS', 
    'XEC', 
    'GPS', 
    'COTY', 
    'UAA', 
    'UA', 
    'NWS', 
    'DB1.DE', 
    'ALV.DE', 
    'SAP.DE', 
    'LHA.DE', 
    '1COV.DE', 
    'FRE.DE', 
    'BEI.DE', 
    'HEN3.DE', 
    'EOAN.DE', 
    'MUV2.DE', 
    'MRK.DE', 
    'FME.DE', 
    'LIN.DE', 
    'BAYN.DE', 
    'SIE.DE', 
    'VNA.DE', 
    'DTE.DE', 
    'BAS.DE', 
    'CON.DE', 
    'RWE.DE', 
    'VOW3.DE', 
    'WDI.DE', 
    'BMW.DE', 
    'ADS.DE', 
    'IFX.DE', 
    'DBK.DE', 
    'DPW.DE', 
    'DAI.DE', 
    'HEI.DE', 
    'TKA.DE', 
    'FIE.DE', 
    'TEG.DE', 
    'SZU.DE', 
    'OSR.DE', 
    'NOEJ.DE', 
    'RRTL.DE', 
    'EVD.DE', 
    'GIL.DE', 
    'FRA.DE', 
    'EVK.DE', 
    'HNR1.DE', 
    'SNH.DE', 
    'GXI.DE', 
    'LEG.DE', 
    'JUN3.DE', 
    'DEQ.DE', 
    'RHK.DE', 
    'ZAL.DE', 
    'LXS.DE', 
    'HOT.DE', 
    'BOSS.DE', 
    'ARL.DE', 
    'KRN.DE', 
    'SHA.DE', 
    'SAZ.DE', 
    'FPE3.DE', 
    'KGX.DE', 
    'MEO.DE', 
    'DUE.DE', 
    'RIB.DE', 
    'GFT.DE', 
    'PFV.DE', 
    'NEM.DE', 
    'QIA.DE', 
    'SOW.DE', 
    'S92.DE', 
    'FNTN.DE', 
    'AFX.DE', 
    'AM3D.DE', 
    'SBS.DE', 
    'SRT3.DE', 
    'O2D.DE', 
    'UTDI.DE', 
    'SMHN.DE', 
    'ADV.DE', 
    'COK.DE', 
    'BC8.DE', 
    'DRW3.DE', 
    'DRI.DE', 
    'COP.DE', 
    'EVT.DE', 
    'NDX1.DE', 
    'O1BC.DE', 
    'MOR.DE', 
    'JEN.DE', 
    'WAF.DE', 
    'AIXA.DE', 
    'DLG.DE', 
    'AC.PA', 
    'AI.PA', 
    'VIV.PA', 
    'RI.PA', 
    'HO.PA', 
    'ATO.PA', 
    'OR.PA', 
    'ORA.PA', 
    'DG.PA', 
    'BN.PA', 
    'GLE.PA', 
    'AIR.PA', 
    'SW.PA', 
    'BNP.PA', 
    'VIE.PA', 
    'CAP.PA', 
    'UG.PA', 
    'FP.PA', 
    'SU.PA', 
    'MC.PA', 
    'ENGI.PA', 
    'ML.PA', 
    'LR.PA', 
    'SAN.PA', 
    'EN.PA', 
    'KER.PA', 
    'ACA.PA', 
    'SGO.PA', 
    'FTI.PA', 
    'CA.PA', 
    'UNA.AS', 
    'IMCD.AS', 
    'PHIA.AS', 
    'AD.AS', 
    'ABN.AS', 
    'GLPG.AS', 
    'HEIA.AS', 
    'ADYEN.AS', 
    'REN.AS', 
    'NN.AS', 
    'RDSA.AS', 
    'AKZA.AS', 
    'ASML.AS', 
    'KPN.AS', 
    'URW.AS', 
    'DSM.AS', 
    'WKL.AS', 
    'ASRNL.AS', 
    'PRX.AS', 
    'AALB.AS', 
    'RAND.AS', 
    'MT.AS', 
    'INGA.AS', 
    'VPK.AS', 
    'AGN.AS' 
]